CREATE SCHEMA "app";
--> statement-breakpoint
CREATE TABLE "app"."dishes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."dishes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"is_soup" boolean DEFAULT false NOT NULL,
	"description" text,
	"img_url" varchar(1024),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."menu_dishes" (
	"menu_id" integer NOT NULL,
	"dish_id" integer NOT NULL,
	CONSTRAINT "menu_dishes_menu_id_dish_id_pk" PRIMARY KEY("menu_id","dish_id")
);
--> statement-breakpoint
CREATE TABLE "app"."menus" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."menus_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"soup_id" integer NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."menus" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."user_choice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."user_choice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"menu_id" integer NOT NULL,
	"dish_id" integer NOT NULL,
	"to_go" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."menu_dishes" ADD CONSTRAINT "menu_dishes_menu_id_menus_id_fk" FOREIGN KEY ("menu_id") REFERENCES "app"."menus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."menu_dishes" ADD CONSTRAINT "menu_dishes_dish_id_dishes_id_fk" FOREIGN KEY ("dish_id") REFERENCES "app"."dishes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."menus" ADD CONSTRAINT "menus_soup_id_dishes_id_fk" FOREIGN KEY ("soup_id") REFERENCES "app"."dishes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_choice" ADD CONSTRAINT "user_choice_menu_id_menus_id_fk" FOREIGN KEY ("menu_id") REFERENCES "app"."menus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_choice" ADD CONSTRAINT "user_choice_dish_id_dishes_id_fk" FOREIGN KEY ("dish_id") REFERENCES "app"."dishes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "app"."dishes" USING btree ("name");--> statement-breakpoint
CREATE INDEX "is_soup_idx" ON "app"."dishes" USING btree ("is_soup");--> statement-breakpoint
CREATE INDEX "date_idx" ON "app"."menus" USING btree ("date");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "app"."user_choice" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "menu_id_idx" ON "app"."user_choice" USING btree ("menu_id");